export const issues = [
    {
        id:1,
        body:"Is there a javascript wrapper for this for Node.js ?",
        title:"feature",
        name:"Sandeep",
        number:1234,
        timeStamp:5,
        message:true,
    },
    {
        id:2,
        body:"Cannot add a team as reviwer.",
        title:"bug",
        name:"ChristopherShyper",
        number:7632,
        timeStamp:15,
    },
    {
        id:3,
        body:"Support for repo update command",
        title:"feature",
        name:"Sandeep",
        number:1234,
        timeStamp:5,
    },
    {
        id:4,
        body:"Changing the file name case sensitivity is not recognized",
        title:"bug",
        name:"ChristopherShyper",
        number:7632,
        timeStamp:15,
        message:true
    },
    {
        id:5,
        body:"Documentation and/or command to update credentials",
        title:"feature",
        name:"jroper",
        number:1234,
        timeStamp:5,
    },
    {
        id:6,
        body:"Default branch and default pull request target as separate things",
        title:"bug",
        name:"j-d-carmichael",
        number:8752,
        timeStamp:25,
        message:true,
    },
    {
        id:7,
        body:"remote add should set usable pushurl",
        title:"feature",
        name:"v4hn",
        number:4725,
        timeStamp:35,
        message:true,
    },
    {
        id:8,
        body:"Says I have unpushed commits when I don't",
        title:"bug",
        name:"redreceipt",
        number:4562,
        timeStamp:20,
    },
    {
        id:9,
        body:"Provide exit code or structured error messages",
        title:"feature",
        name:"loosebazooka",
        number:2543,
        timeStamp:27,
    },
    {
        id:10,
        body:"Default branch and default pull request target as separate things",
        title:"bug",
        name:"j-d-carmichael",
        number:8752,
        timeStamp:25,
        message:true,
    },
    {
        id:11,
        body:"hub create in an organization without a visibility flag should use",
        title:"feature",
        name:"davidstosik",
        number:9754,
        timeStamp:15,
    },
    {
        id:12,
        body:"Documentation request for personal access tokens",
        title:"bug",
        name:"schooljan",
        number:4532,
        timeStamp:8,
    },
    {
        id:13,
        body:"Version displays incorrectly of hub in terminal",
        title:"bug",
        name:"jefferythomas",
        number:2386,
        timeStamp:35,
    },
    {
        id:14,
        body:"Please release for linux/ppc64le too",
        title:"feature",
        name:"ezeeyahoo",
        number:9754,
        timeStamp:15,
        message:true,
    },
    {
        id:15,
        body:"Auto-merge PRs created by hub",
        title:"feature",
        name:"zoispag",
        number:2856,
        timeStamp:40,
    },   
  ]